#!/bin/bash
show_table() {
	_row0=$'\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2566\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557'
	_row1=$'\u2551\u0020bold\u0020\u2551\u0020bold\u0020\u2551'
	_row2=$'\u2551\u0020underline\u0020\u2551\u0020rmul\u0020\u2551'
	_row3=$'\u2551\u0020underline\u0020\u2551\u0020rmul\u0020\u2551'
	printf "\t%s\n" $_row0
	printf "\t%s\n" $_row1
	printf "\t%s\n" $_row2
	printf "\t%s\n" $_row3
	printf "\n\r"
	exit 0;
}

showcolors_help() {
	tput bold
	printf "\tShow Colors by Stephen Harold Smith.\n\n\r"
	printf "\tAdd a number as first argument to set the background color..\n\r\tExample, show white background:\n\r\tsh showcolors 15\n\n\r"
	printf "\t-h --help\tShow this help text.\n\r"
	printf "\t-t --table\tShow available tput commands\n\r"
	printf "\n\r"
	tput sgr0
}

#_sc() {
#n=$0
#_one2ten=$1

#}

showcolors() {
	_one2ten=1
	for n in {1..254}
	do
		tput setaf $n
		[ $_one2ten = 1 ] && printf "\t<|"

		if [[ "$1" =~ [0-9] ]];
		then
			tput setab $1
			printf "|> %03d <|" "$n"
		elif [[ "$1" =~ -h ]];
		then
			tput sgr0
			showcolors_help
			return 0;
		elif [[ "$1" =~ -t ]];
		then
			tput sgr0
			show_table
			return 0;
		else
			printf "|> %03d <|" "$n"
		fi

		tput sgr0
	    [ $_one2ten = 10 ] && _one2ten=0 && printf "|>\n\r"

	:   $((_one2ten++))
#	    sleep 0.0015
	done
	printf "%s\n\r\n\r" "$(tput sgr0)"

	echo "PALETTE OF 8 COLORS (bold, high intensity, normal, faint)"
	for i in {30..37}; do printf "\e[1;${i}m1;%-2s\t\e[m" "$i"; done; echo
	for i in {90..97}; do printf "\e[${i}m%+4s\t\e[m" "$i"; done; echo
	for i in {30..37}; do printf "\e[${i}m%+4s\t\e[m" "$i"; done; echo
	for i in {30..37}; do printf "\e[2;${i}m2;%-2s\t\e[m" "$i"; done;

	echo "\n\n\nPALETTE OF 256 COLORS (only normal)"
	j=8
	for i in {0..255}; do
	    [[ $i = 16 ]] && j=6
	    [[ $i = 232 ]] && j=8
	    printf "\e[38;5;${i}m38;5;%-4s\e[m" "${i}"
#		sleep 0.015
	    (( i>15 && i<232 )) && printf "\e[52C\e[1;38;5;${i}m1;38;5;%-4s\e[52C\e[m\e[2;38;5;${i}m2;38;5;%-4s\e[m\e[126D" "${i}" "${i}"

	    [[ $(( $(( $i - 15 )) % $j )) = 0 ]] && echo
	    [[ $(( $(( $i - 15 )) % $(( $j * 6 )) )) = 0 ]] && echo

	done
}

showcolors $@
